const PRODUCTS = [
  { title: "生成新聞", category: "AI News Service" },
  { title: "MAGI SYSTEM", category: "AI Discussion Platform" },
  { title: "AI COPYWRITER GHOST", category: "Creative Tool" },
  { title: "MY RANKING", category: "Interactive Web App" },
  { title: "NIGHT QUEEN", category: "Browser Game" },
  { title: "まちのカルテ", category: "Data Visualization" },
  { title: "Generated by We TAIWAN", category: "AI News Translation" },
  { title: "ClipboardGuard", category: "Developer Tool" },
];

export default function Home() {
  return (
    <main
      style={{
        minHeight: "100vh",
        backgroundColor: "#0a0a0c",
        color: "#f5f5f5",
        fontFamily:
          "'JetBrains Mono', 'SF Mono', 'Fira Code', monospace",
      }}
    >
      {/* Hero */}
      <section
        style={{
          padding: "80px 40px 60px",
          maxWidth: "960px",
          margin: "0 auto",
        }}
      >
        <p
          style={{
            fontSize: "13px",
            color: "#1D9E75",
            letterSpacing: "0.15em",
            marginBottom: "16px",
          }}
        >
          AI STUDIO PAUL
        </p>
        <h1
          style={{
            fontSize: "clamp(32px, 5vw, 48px)",
            fontWeight: 600,
            lineHeight: 1.3,
            margin: "0 0 20px",
            fontFamily:
              "'Noto Sans JP', 'Hiragino Kaku Gothic ProN', sans-serif",
          }}
        >
          OGP Image API
        </h1>
        <p
          style={{
            fontSize: "16px",
            color: "#999",
            lineHeight: 1.7,
            maxWidth: "600px",
          }}
        >
          URLにタイトルとカテゴリを渡すだけで、ブランド統一されたOGP画像（1200x630px）を動的に生成するAPI。
        </p>
      </section>

      {/* Usage */}
      <section
        style={{
          padding: "0 40px 60px",
          maxWidth: "960px",
          margin: "0 auto",
        }}
      >
        <h2
          style={{
            fontSize: "14px",
            color: "#1D9E75",
            letterSpacing: "0.12em",
            marginBottom: "20px",
          }}
        >
          USAGE
        </h2>
        <div
          style={{
            backgroundColor: "#161619",
            borderRadius: "12px",
            padding: "24px",
            border: "1px solid #222",
          }}
        >
          <code
            style={{
              fontSize: "14px",
              color: "#e0e0e0",
              wordBreak: "break-all",
            }}
          >
            GET /api/og?<span style={{ color: "#1D9E75" }}>title</span>=
            生成新聞&<span style={{ color: "#1D9E75" }}>category</span>=AI
            News Service
          </code>
        </div>

        <div
          style={{
            marginTop: "32px",
            display: "grid",
            gridTemplateColumns: "1fr 1fr",
            gap: "16px",
          }}
        >
          <div
            style={{
              backgroundColor: "#161619",
              borderRadius: "8px",
              padding: "20px",
              border: "1px solid #222",
            }}
          >
            <p
              style={{
                fontSize: "12px",
                color: "#1D9E75",
                letterSpacing: "0.1em",
                marginBottom: "8px",
              }}
            >
              TITLE
            </p>
            <p style={{ fontSize: "14px", color: "#ccc", margin: 0 }}>
              プロダクト名（日本語・英語OK）
            </p>
          </div>
          <div
            style={{
              backgroundColor: "#161619",
              borderRadius: "8px",
              padding: "20px",
              border: "1px solid #222",
            }}
          >
            <p
              style={{
                fontSize: "12px",
                color: "#1D9E75",
                letterSpacing: "0.1em",
                marginBottom: "8px",
              }}
            >
              CATEGORY
            </p>
            <p style={{ fontSize: "14px", color: "#ccc", margin: 0 }}>
              カテゴリ名（例: AI News Service）
            </p>
          </div>
        </div>

        {/* meta tag example */}
        <h2
          style={{
            fontSize: "14px",
            color: "#1D9E75",
            letterSpacing: "0.12em",
            marginTop: "48px",
            marginBottom: "20px",
          }}
        >
          HTML META TAG
        </h2>
        <div
          style={{
            backgroundColor: "#161619",
            borderRadius: "12px",
            padding: "24px",
            border: "1px solid #222",
            fontSize: "13px",
            lineHeight: 1.8,
            color: "#e0e0e0",
            overflowX: "auto",
          }}
        >
          <pre style={{ margin: 0, whiteSpace: "pre-wrap" }}>
{`<meta property="og:image"
  content="https://og-api-self.vercel.app/api/og
    ?title=生成新聞&category=AI News Service" />
<meta property="og:image:width" content="1200" />
<meta property="og:image:height" content="630" />
<meta name="twitter:card"
  content="summary_large_image" />`}
          </pre>
        </div>
      </section>

      {/* Gallery */}
      <section
        style={{
          padding: "0 40px 80px",
          maxWidth: "960px",
          margin: "0 auto",
        }}
      >
        <h2
          style={{
            fontSize: "14px",
            color: "#1D9E75",
            letterSpacing: "0.12em",
            marginBottom: "24px",
          }}
        >
          GALLERY
        </h2>
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fill, minmax(400px, 1fr))",
            gap: "20px",
          }}
        >
          {PRODUCTS.map((p) => (
            <div key={p.title} style={{ borderRadius: "8px", overflow: "hidden" }}>
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={`/api/og?title=${encodeURIComponent(p.title)}&category=${encodeURIComponent(p.category)}`}
                alt={`${p.title} OGP`}
                style={{ width: "100%", height: "auto", display: "block" }}
              />
            </div>
          ))}
        </div>
      </section>

      {/* Footer */}
      <footer
        style={{
          padding: "40px",
          textAlign: "center",
          fontSize: "13px",
          color: "#555",
          borderTop: "1px solid #1a1a1a",
        }}
      >
        MADE WITH VIBE CODING — AI STUDIO PAUL
      </footer>
    </main>
  );
}
